CREATE TABLE IF NOT EXISTS suppliers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    contact_name VARCHAR(150),
    phone VARCHAR(50),
    email VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE suppliers
    ADD COLUMN IF NOT EXISTS contact_name VARCHAR(150);

ALTER TABLE suppliers
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50);

ALTER TABLE suppliers
    ADD COLUMN IF NOT EXISTS email VARCHAR(255);

ALTER TABLE suppliers
    ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE suppliers
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE items
    ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES suppliers(id);

ALTER TABLE stock_movements
    ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES suppliers(id);

ALTER TABLE items
    DROP CONSTRAINT IF EXISTS items_sku_key;

ALTER TABLE items
    DROP COLUMN IF EXISTS sku;
